spring:
  profiles: test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE

---

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/harjoitus
    username: harkka
    password: harkka123
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop